/* eslint-disable @typescript-eslint/no-explicit-any */
/** Renders Markdown evidence from the saved JSON results (no numbers are typed by hand). */
import fs from "node:fs";
import { prisma } from "@/lib/database/prisma";

const read = (f: string) => JSON.parse(fs.readFileSync(`docs/evaluation/${f}`, "utf8"));
const esc = (s: unknown) => String(s ?? "—").replace(/\|/g, "\\|").replace(/\n/g, " ");

function retrievalTable(title: string, rep: { note?: string; summary: Record<string, number>; results: Record<string, any>[] }) {
  const s = rep.summary;
  return [
    `### ${title}`, "", rep.note ? `_${rep.note}_` : "", "",
    `**${s.correct} correct · ${s.partiallyCorrect} partially correct · ${s.incorrect} incorrect** (of ${s.total}) · warm retrieval P50 ${s.p50LatencyMs} ms / P95 ${s.p95LatencyMs} ms · cold start ${s.coldStartMs} ms`, "",
    "| # | Type | User question | Retrieved record | Source reference | Relevance explanation | Answer given | Verdict |",
    "|---|---|---|---|---|---|---|---|",
    ...rep.results.map((r) => `| ${r.id} | ${r.type} | ${esc(r.question)} | ${r.retrieved ? `\`${r.retrieved.recordId}\` ${esc(r.retrieved.title)}${r.grounded ? "" : " _(not grounded)_"}` : "—"} | ${esc(r.sourceReference)} | ${esc(r.relevanceExplanation)} | ${esc(r.answer)} | **${r.verdict}** |`),
    "",
  ].join("\n");
}

async function main() {
  const md = [
    "# Q2 – Retrieval evaluation", "",
    "Generated by `npx tsx scripts/render-reports.ts` from the JSON results in this folder. The verdict is computed automatically: **correct** = the top grounded record is one of the expected records (for out-of-scope questions: the system refused); **partially correct** = an acceptable record is on top, or an expected record is in the top 3; **incorrect** = anything else, including refusing an answerable question.", "",
    "Honesty note: the development set was also used to tune synonyms and thresholds, so its score is optimistic. **The held-out sets are the numbers to trust.**", "",
    retrievalTable("Held-out v2 (clean: written before the final changes, run once)", read("retrieval-heldout-v2.json")),
    retrievalTable("Held-out v1 – first run, before the cross-encoder reranker", read("retrieval-heldout-v1-before-rerank.json")),
    retrievalTable("Held-out v1 – re-run after adding the reranker (thresholds chosen on dev only)", read("retrieval-heldout.json")),
    retrievalTable("Development set (used for tuning)", read("retrieval-eval.json")),
  ].join("\n");
  fs.writeFileSync("docs/evaluation/RETRIEVAL_EVALUATION.md", md);

  // sample records: one of each interesting status
  const pick = async (where: object) => prisma.kbRecord.findFirst({ where, orderBy: { recordId: "asc" } });
  const samples = (await Promise.all([pick({ recordId: "kb_partnership_001" }), pick({ category: "objection" }), pick({ containsPii: true }), pick({ status: "duplicate" }), pick({ status: "superseded" }), pick({ status: "flagged" })])).filter(Boolean);
  fs.writeFileSync("docs/evaluation/sample-records.json", JSON.stringify(samples.map((r) => ({ record_id: r!.recordId, title: r!.title, content: r!.content, category: r!.category, product_line: r!.productLine, source: r!.source, source_ref: r!.sourceRef, version: r!.version, contains_pii: r!.containsPii, pii_types: r!.piiTypes, status: r!.status, duplicate_of: r!.duplicateOf, content_hash: r!.contentHash, metadata: r!.metadata })), null, 2));

  const q1 = read("q1-test-calls.json");
  fs.writeFileSync("docs/evaluation/Q1_TEST_CALLS.md", [
    "# Q1 – Recorded test calls", "", `_${q1.method}_`, "",
    `**${q1.summary.passed}/${q1.summary.total} calls passed all checks (${q1.summary.checksPassed}/${q1.summary.checksTotal} checks); mean caller-side ASR WER ${q1.summary.meanWer}.**`, "",
    "| Scenario | Outcome | Qualification | Escalated | Actions | Checks | Caller WER | Recording · transcript |", "|---|---|---|---|---|---|---|---|",
    ...q1.calls.map((c: any) => `| ${c.title} | ${c.outcome} | ${c.qualification ?? "—"} | ${c.escalated} | ${[...new Set(c.actions)].join(", ") || "—"} | ${c.checks.map((k: any) => `${k.pass ? "✅" : "❌"} ${k.name}`).join("<br>")} | ${c.meanWer} | [wav](../../public/${c.recording}) · [md](../../public/${c.recording.replace(".wav", ".md")}) |`),
    "",
  ].join("\n"));

  const asr = read("q3-asr.json"), dev = read("q3-tests.json"), v1 = read("q3-tests-heldout-v1.json"), v2 = read("q3-tests-heldout-v2.json"), calls = read("q3-calls.json");
  fs.writeFileSync("docs/evaluation/Q3_RESULTS.md", [
    "# Q3 – Measured results (generated)", "",
    "## Conversation tests (language/register detection, intent, in-language replies, escalation)", "",
    `- Held-out v2 (clean): **${v2.summary.passed}/${v2.summary.total} checks passed**`,
    `- Held-out v1, first run (before general fixes): ${v1.summary.passed}/${v1.summary.total}`,
    `- Same set after the fixes (now a development set): ${dev.summary.passed}/${dev.summary.total}`, "",
    "Failed checks in held-out v2:", "",
    ...v2.cases.flatMap((c: any) => c.turns.flatMap((t: any) => t.checks.filter((k: any) => !k.pass).map((k: any) => `- ${c.market} "${t.text}" → ${k.name}`))), "",
    "## Recorded calls (2 per market)", "", "| Call | Outcome | Mean caller WER | Recording · transcript |", "|---|---|---|---|",
    ...calls.calls.map((c: any) => `| ${c.title} | ${c.outcome} | ${c.meanWer} | [wav](../../public/${c.recording}) · [md](../../public/${c.recording.replace(".wav", ".md")}) |`), "",
    "## ASR (Whisper, local) on synthesized speech", "", `_${asr.caveat}_`, "",
    "| Market · voice · model · forced language | Mean WER | Mean latency (ms) |", "|---|---|---|",
    ...asr.summary.map((s: any) => `| ${s.config} | ${s.meanWer} | ${s.meanLatencyMs} |`), "",
    "Per category (whisper-small, market language forced):", "", "| Market · voice · category | Mean WER |", "|---|---|",
    ...asr.categoriesWhisperSmallForced.map((s: any) => `| ${s.config} | ${s.meanWer} |`), "",
    "Every utterance (reference vs hypothesis):", "", "| Market | Voice | Model | Lang | Reference | Hypothesis | WER |", "|---|---|---|---|---|---|---|",
    ...asr.rows.filter((r: any) => r.model.endsWith("small")).map((r: any) => `| ${r.market} | ${r.voice} | small | ${r.language} | ${esc(r.reference)} | ${esc(r.hypothesis)} | ${r.wer} |`), "",
  ].join("\n"));
  console.log("rendered RETRIEVAL_EVALUATION.md, Q1_TEST_CALLS.md, Q3_RESULTS.md, sample-records.json");
  await prisma.$disconnect();
}
main();
